# docker-compose.yml
version: "3"
services:
  web:
    image: php:7.4-apache
    ports:
    - "8080:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
