version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  backend1:
    image: nginx
    container_name: backend1
    volumes:
    - ../web1/index.html:/usr/share/nginx/html/index.html
  backend2:
    image: nginx
    container_name: backend2
    volumes:
    - ../web2/index.html:/usr/share/nginx/html/index.html
