apiVersion: v1
kind: ConfigMap
metadata:
  name: amqp-connect-config
data:
  AMQP_URL: 'amqp://guest:guest@rabbitmq-service:5672'
  AMQP_QUEUE: 'my-queue'
  AMQP_EXCHANGE: 'my-exchange'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-receive
  labels:
    app: amqp-receive
spec:
  selector:
    matchLabels:
      app: amqp-receive
  template:
    metadata:
      name: amqp-receive
      labels:
        app: amqp-receive
    spec:
      containers:
        - name: amqp-receive
          image: kaylleur/amqp-receive:1.0.1
          envFrom:
            - configMapRef:
                name: amqp-connect-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-send
  labels:
    app: amqp-send
spec:
  selector:
    matchLabels:
      app: amqp-send
  template:
    metadata:
      name: amqp-send
      labels:
        app: amqp-send
    spec:
      containers:
        - name: amqp-send
          image: kaylleur/amqp-send:1.0.1
          envFrom:
            - configMapRef:
                name: amqp-connect-config
