version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./traefik.yml:/etc/traefik/traefik.yml:ro"
    - "./certs:/certs:ro"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: traefik/whoami
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=Host(`localhost`)"
    - "traefik.http.routers.whoami.entrypoints=websecure"
    - "traefik.http.routers.whoami.tls=true"